### ISSUE TITLE
Script to rebuild and reinstall commands

### ISSUE THREAD

**Issue by flomotlik** [whalebrew/whalebrew-packages#30]
For developing locally it might be neat to have a script in the root that allows to rebuild a container, uninstall the old and reinstall the new one (in case labels have changed).

Happy to provide the script (bash or Makefile or whatevery you guys want), just wanted to check in if that makes sense and what else the script should do.

**Comment by mapitman** [comment]
That's a great idea. My preference would be Makefiles in each package and then one at the top level that builds them all, but that's just me and I am not an owner of the project 😄

**Comment by flomotlik** [comment]
@mapitman since the build process should be completely the same for every container I think we should be able to do it with one root script and you simply give it the folder to build. Makefile sounds fine to me in general, lets see what @bfirsh thinks

**Comment by bfirsh** [comment]
Sounds great! :+1:

No strong feelings about what system is used. Slight leaning towards just a shell script, because there's nothing from make we're actually using, so it seems an unnecessary dependency.

Agreed it should be just a single script, because each package has to be the same build process.

**Comment by flomotlik** [comment]
#43 has a Reinstall script now that completely rebuilds the container and force installs over an existing one. @mapitman it also supports handing it multiple folders so you could easily rebuild all containers with it.

Potentially this could be used for CI (with an additional validation step) and for deploying those containers without having to set up builds on Dockerhub, but thats something we should discuss sometime later I guess if wanted.
