### ISSUE TITLE
Automatically configure Docker Cloud builds

### ISSUE THREAD

**Issue by bfirsh** [whalebrew/whalebrew-packages#7]
Currently, I'm manually clicking through the Docker Cloud UI to add each image. This could probably represented as a file in the root of this repository, specifying what repos need to exist, and what tags need to be on each repo, then a CI job can ensure Docker Cloud is in the correct state on each commit.

**Comment by LongLiveCHIEF** [comment]
Let me know if you want some help with this.  I'd like to work on whalebrew tooling this weekend. 

Let me know if there's an irc/slack/gitter you hang out on, or alternatively you can hop into our [Hacker Happy Hour discord chat room](https://discord.gg/8kC3E)

**Comment by mapitman** [comment]
I'd be interested in helping too. Haven't done anything with Docker Cloud before, but it would be fun to learn!

**Comment by bfirsh** [comment]
The [official API](https://docs.docker.com/apidocs/docker-cloud/) doesn't have support for adding repositories or automated builds, but the Cloud team might be able to help us out. (hi @fermayo ;)
